# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: dbos-app-starter
language: python
env:
  RUNTIME_COMMAND: "${RUNTIME_COMMAND}"
runtimeConfig:
  start:
    - ${RUNTIME_COMMAND}
database:
  migrate:
    - echo 'No migrations specified'
telemetry:
  logs:
    logLevel: INFO
